"""Write the minimal ``<dag>/dag.py`` that wires every YAML through the TaskGroup builder."""
from __future__ import annotations

from pathlib import Path


CADENCE_TO_SCHEDULE = {
    "daily": "@daily",
    "weekly": "@weekly",
    "monthly": "@monthly",
}


_TEMPLATE = '''\
"""Generated by common_lib.create_dag — regenerate instead of editing."""
from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path

from airflow import DAG

from common_lib.tasks.build_table_taskgroup import build_table_taskgroup

HERE = Path(__file__).resolve().parent

default_args = {
    "owner": "allen",
    "depends_on_past": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "email_on_failure": False,
    "email_on_retry": False,
}

with DAG(
    dag_id=HERE.name,
    description=f"ETL for {HERE.name} -> Azure Blob",
    start_date=datetime(2026, 1, 1),
    schedule=__SCHEDULE__,
    catchup=False,
    default_args=default_args,
    tags=[HERE.name, "azure_blob", "etl"],
    max_active_runs=1,
):
    for yaml_path in sorted((HERE / "table").glob("*.yaml")):
        build_table_taskgroup(yaml_path)
'''


def write_dag_file(dag_dir: Path, cadence: str) -> Path:
    schedule = CADENCE_TO_SCHEDULE.get(cadence.lower())
    if schedule is None:
        raise ValueError(
            f"Unknown cadence {cadence!r}; expected one of {sorted(CADENCE_TO_SCHEDULE)}"
        )
    out_path = dag_dir / "dag.py"
    out_path.write_text(_TEMPLATE.replace("__SCHEDULE__", repr(schedule)))
    return out_path
