#!/usr/bin/env python3
"""Embed selected `common_lib` sources into `docs/obsidian/code/*.md` for Obsidian.

Run from repo root:
    python3 docs/obsidian/sync_code_snippets.py

Re-run whenever Python changes and you want vault snapshots updated.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "docs" / "obsidian" / "code"

# (markdown_filename, path_under_repo, one_line_description)
FILES: list[tuple[str, str, str]] = [
    ("read_excel.md", "common_lib/intake/read_excel.py", "Intake reader → `read_intake_rows`."),
    ("group_by_dag.md", "common_lib/intake/group_by_dag.py", "`dag_id_for`, `group_by_dag`."),
    ("create_dag.md", "common_lib/create_dag.py", "CLI + `generate()` sync."),
    ("build_table_taskgroup.md", "common_lib/tasks/build_table_taskgroup.py", "Airflow TaskGroup wiring."),
    ("connector_class_init.md", "common_lib/connector_class/__init__.py", "`IMPORT_CONNECTORS` / `EXPORT_CONNECTORS`."),
    ("write_dag_file.md", "common_lib/scaffold/write_dag_file.py", "Scaffold `dag.py` from cadence."),
    ("write_table_yaml.md", "common_lib/scaffold/write_table_yaml.py", "`build_table_yaml_payload`, `write_table_yaml`."),
    ("write_extract_task.md", "common_lib/scaffold/write_extract_task.py", "Template for `task/extract.py`."),
    ("write_upload_task.md", "common_lib/scaffold/write_upload_task.py", "Template for `task/upload.py`."),
    ("scaffold_init.md", "common_lib/scaffold/__init__.py", "Scaffold package docstring."),
]


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for md_name, rel, blurb in FILES:
        src_path = ROOT / rel
        text = src_path.read_text(encoding="utf-8")
        stem = md_name.replace(".md", "")
        body = f"""---
tags:
  - source-snapshot
---

# `{rel}`

> Auto-generated by `docs/obsidian/sync_code_snippets.py`. **Re-run the script** after editing the Python file.

{blurb}

← [[00 - Index|Back to Index]]

```python
{text.rstrip()}
```
"""
        (OUT_DIR / md_name).write_text(body, encoding="utf-8")
        print("wrote", OUT_DIR / md_name)
    print("done:", len(FILES), "files")


if __name__ == "__main__":
    main()
